### ISSUE TITLE
Unable to run container behind Traefik Proxy with Path rule

### ISSUE THREAD

**Issue by ichhabkeinbock** [mwalbeck/docker-cyberchef#1]
I'm desperately trying to run CyberChef behind traefik, all the containers I tried so far were not working. Even building from source...
Anyway. This is my docker-compose.yml:

```yaml
version: "3.3"
services:
  traefik:
    image: "traefik:latest"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
  
  whoami:
    image: "traefik/whoami"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`localhost`) && Path(`/whoami/`)"
      - "traefik.http.routers.whoami.entrypoints=web"
  
  cyberchef:
    image: "mwalbeck/cyberchef:latest"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cyberchef.rule=Host(`localhost`) && Path(`/cyberchef/`)"
      - "traefik.http.routers.cyberchef.entrypoints=web"

  nginx:
    image: "nginx"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=Host(`localhost`)"
      - "traefik.http.routers.nginx.entrypoints=web"
    volumes:
      - ./static:/usr/share/nginx/html
```

When removing ```Path(`/cyberchef`)``` from the docker and removing the nginx container with the same rule, the application will run at `localhost`. So Cyberchef is working. But as soon, as I use the Path() rule, I get a 404 and the following traceback from the docker compose command:

```
mytoolbox-cyberchef-1  | 2022/10/28 12:54:30 [error] 29#29: *1 "/usr/share/nginx/html/cyberchef/index.html" is not found (2: No such file or directory), client: 172.18.0.5, server: localhost, request: "GET /cyberchef/ HTTP/1.1", host: "localhost"
mytoolbox-cyberchef-1  | 172.18.0.5 - - [28/Oct/2022:12:54:30 +0000] "GET /cyberchef/ HTTP/1.1" 404 555 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36" "172.18.0.1"
```

Any ideas what the issue is?
